### ISSUE TITLE
Missing install/build instructions

### ISSUE THREAD

**Issue by schnuffle** [cutelyst/Virtlyst#14]
I've been using webvirtmgr and as a replacement kimchi and wanted to see how I might use Virtlyst in my setup.
But I'm a bit lost on howto setup your stuff as there's no docs about it or I'm just to dump to find them.

**Comment by renlinch** [comment]
Build is simple Download and cmake if you have cutelyst >2.5 installed.

To install Cutelyst: [https://github.com/cutelyst/cutelyst/wiki/Installing-Cutelyst](https://github.com/cutelyst/cutelyst/wiki/Installing-Cutelyst)

Me openSUSE using buschmann23 repo [https://software.opensuse.org/package/cutelyst2](https://software.opensuse.org/package/cutelyst2)

Then Download the Release from : [https://github.com/cutelyst/Virtlyst/releases](https://github.com/cutelyst/Virtlyst/releases) and.
Example V1.2.0 for me it is in "/home/usr/bin" :
```
.../>wget https://github.com/cutelyst/Virtlyst/archive/v1.2.0.tar.gz
.../>tar xzf v1.2.0.tar.gz
.../>cd Virtlyst-1.2.0/
.../Virtlyst-1.2.0> mkdir build
.../Virtlyst-1.2.0> cd build/
.../Virtlyst-1.2.0/build> cmake ..
...
.../Virtlyst-1.2.0/build> make'
...
[100%] Linking CXX shared library libVirtlyst.so
[100%] Built target Virtlyst
.../Virtlyst-1.2.0/build>
```

When done copy or move it to where you would have it (Maybe there is a install routine but i didn't use it) to where you would have it. For me i leave it as it is. And run it with the Command as the user usr:
```
.../Virtlyst-1.2.0/build> cd ..
.../Virtlyst-1.2.0>cutelyst-wsgi2 --application ./build/src/libVirtlyst.so --chdir2 . --static-map /static=root/static --http-socket localhost:3000 --master
Installing EPoll event loop
Cutelyst-WSGI starting
WSGI socket 0 bound to TCP address 0.0.0.0:3000 fd 7
Loading application: ./build/src/libVirtlyst.so
30991:30991 cutelyst.core[warning] Can not load translations from not existing directory: "/usr/share/cutelyst2/translations"
Changing directory2 to: .
30991:30991 virtlyst[debug] Production false
30991:30991 virtlyst[debug] Database "/home/usr/virtlyst.sqlite"
30991:30991 virtlyst[debug] Creating database "/home/usr/virtlyst.sqlite"
30991:30991 virtlyst[debug] PRAGMA journal_mode = WAL true ""
30991:30991 virtlyst[critical] Created user admin with password: "xxxxxxxxx"
30991:30991 cutelyst.core[warning] Can not load translations from not existing directory: "/usr/share/cutelyst2/translations"
spawned WSGI master process (pid: 30991)
spawned WSGI worker (and the only) (pid: 30995, cores: 1)
30995:30995 virtlyst[debug] Database ready "virtlyst-0"
```

Don't forget to note the initial Password for admin somewhere. 

Now it should work (for me it asks for root rights when executed as user, else you could run it as root.) 
Access it via http://localhost:3000 from a browser of your choice.
For Internal Systems it worked until now on 12 Hosts as root user.  

On the production machine i copied the root and application to /opt/virtlyst/. and replaced the execution with the other directory and run as root, binded at internal IP Address with no external access to others than the Administrators (via VPN).

Greeting

**Comment by schnuffle** [comment]
Thanxs for the infos. I'm a bit busy right now and as my project needed a solution instantly, I used another option.
Though i'm still interested and will try to test it as soon as I find some spare time

Regards

Schnuffle
