### ISSUE TITLE
Username setting for qemu+ssh:// doesn't work

### ISSUE THREAD

**Issue by dvolk** [cutelyst/Virtlyst#15]
Version 1.1.0, but looking at the commits I can't see a fix

The username setting for ssh connections seems to be ignored. I set it but it uses the local username / username running Virtlyst

**Comment by gagrilli** [comment]
I too am experiencing the same behaviour. 
Virtlyst compiled fine, works ok on local libvirt via socket, but not on remote ssh URIs

Opensuse Leap 15.0, qemu: 3.0.0-lp150.476.5 
                                   libvirt:   4.4.0-lp150.751.1 
                                   virtlyst: 1.2.0, compiled as per [this](https://github.com/cutelyst/Virtlyst/issues/14#issuecomment-423440679) post from @renlinch

**Comment by dantti** [comment]
I'm quite busy ATM, I can review patches but will only be able to look into this in 1 month or so
