### ISSUE TITLE
Releases do not have a Branch or Tag

### ISSUE THREAD

**Issue by schnuffle** [cutelyst/Virtlyst#19]
I'm back to test Virtlyst for using it on a CentOS7 box.

Now I see several Releases but there's no connection between any Tag or Branch and a Release. I would suggest that for each Release, there should be at least a Tag to be able to build from the cloned Repo.

regards

Schnuffle

**Comment by dantti** [comment]
of course there's a connection, in GitHub all releases are tags:
https://github.com/cutelyst/Virtlyst/tags
I'm really confused by what do you mean.

**Comment by schnuffle** [comment]
Hi Dantti
Sorry the confusion has been on my side. Firefox doesn't open the branch/tag dropdown after the latest Update and I didn't check on the command line.
So, my bad

**Comment by schnuffle** [comment]
Closing obsolete Issue
