### ISSUE TITLE
Console wont connect to VMs on external HOST 

### ISSUE THREAD

**Issue by emdo-pa** [cutelyst/Virtlyst#28]
As in topic, WebConsole aquires IP address from VMS config and tries to connect to 127.0.0.1 or 0.0.0.0 on port 5900 (for the first VM).  To be able to connect I was forced to manualy edit XML and set the address to some routable  address.

A good starting pooint would be to take an IP from the  Host's Connection details (when used as a qemu+ssh/tcp/tls)

**Comment by dantti** [comment]
That's exactly what is done but address must be set to 0.0.0.0 as 127.0.0.1 won't allow remote connections:
https://github.com/cutelyst/Virtlyst/blob/master/src/ws.cpp#L47

**Comment by emdo-pa** [comment]
seems it doesnt work in my case, 
CUTELYST_VERSION=v2.6.0
VIRTLYST_VERSION=v1.2.0

in logs i can see:
`6:8 virtlyst.ws[debug] Connecting TCP socket to "0.0.0.0" 5900
6:8 virtlyst.ws[warning] Console Proxy error: QAbstractSocket::ConnectionRefusedError "Connection refused"`

in XML of a VM I had set:
`    <graphics listen="0.0.0.0" autoport="yes" port="5900" passwd="TryToGuess" type="spice">
      <listen address="0.0.0.0" type="address"/>
      <image compression="off"/>
    </graphics>`

and on a HOST system, port is open and listening
`tcp        0      0 0.0.0.0:5900            0.0.0.0:*               LISTEN      7097/qemu-system-x86....`

Virtlyst is using QEMU+SSH to a host 192.168.4.10

**Comment by dantti** [comment]
This is fixed in git master, I haven't tagget a Virtlyst release after that yet

**Comment by misery** [comment]
Is it possible to use ssh to redirect if 127.0.01 is used? I'm using localhost and virt-manager can do this with ssh without any problems. Maybe libvirt already supports it?

**Comment by dantti** [comment]
Both use libvirt under the hood so likely possible, the main issue with SSH is if it want's to prompt for password, you better use ssh-keys then

**Comment by misery** [comment]
> Both use libvirt under the hood so likely possible, the main issue with SSH is if it want's to prompt for password, you better use ssh-keys then

Yeah, I already added ssh key and it works perfect. Just the console is not working because I like to use localhost and authorization over ssh.
Do you have a hint for me where libvirt is called in Virtlyst? So I can look into it.

**Comment by dantti** [comment]
hmm don't know exactly what you want, but likely https://github.com/cutelyst/Virtlyst/blob/master/src/lib/connection.cpp
