### ISSUE TITLE
Consoles wont connect when using HTTPS and reverse proxy

### ISSUE THREAD

**Issue by jpann** [cutelyst/Virtlyst#31]
Consoles won't connect when using HTTPS and reverse proxy (https://github.com/jwilder/nginx-proxy). Switching connection to virtlyst instance to HTTP lets consoles connect. Tried VNC and SPICE.

UI error: `Server disconnected (code: 1006)`
Log: `7:15 grantlee.customtype[warning] Don't know how to handle metatype QString
`

**Comment by dantti** [comment]
I do use it behind NGINX with HTTPS.

The log info is unrelated.

Please try to see what's happening on your browser's console, perhaps you are not setting the proper HTTP headers for reverse proxy:

    location /ws {
        #proxy_pass http://localhost:8000;
        proxy_pass http://localhost:3001;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-for $proxy_add_x_forwarded_for;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 600;
        proxy_read_timeout 600;
        client_max_body_size 1024M; # Set higher depending on your needs 
    }

**Comment by jpann** [comment]
> I do use it behind NGINX with HTTPS.
> 
> The log info is unrelated.
> 
> Please try to see what's happening on your browser's console, perhaps you are not setting the proper HTTP headers for reverse proxy:
> 
> ```
> location /ws {
>     #proxy_pass http://localhost:8000;
>     proxy_pass http://localhost:3001;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-for $proxy_add_x_forwarded_for;
>     proxy_set_header Host $host:$server_port;
>     proxy_set_header X-Forwarded-Proto $scheme;
>     proxy_connect_timeout 600;
>     proxy_read_timeout 600;
>     client_max_body_size 1024M; # Set higher depending on your needs 
> }
> ```

That worked. thanks!
