### ISSUE TITLE
Console via squid proxy

### ISSUE THREAD

**Issue by haralambop** [cutelyst/Virtlyst#32]
The vnc/spice console is not working when using a squid proxy.

**Comment by dantti** [comment]
Please elaborate your issue, it's too vague and it's likely that the problem is at squid configuration.
Does it allows websockets?

**Comment by haralambop** [comment]
I am using squid with the following specs: 
squid -v

Listening on

http_port 3128 transparent
http_port 3129

with the default settings.

All pages are working fine ( with/without proxy ) except the VM console. 
When using the proxy the vnc console is not working.
(Server disconnected (code: 1006))

here the console of the browser:

connecting to ws://192.168.0.10:80/ws/1/fed78575-7f74-4ae0-9bbd-1f3c54e170c8 util.js:109:61
Detected binaryType support in WebSockets util.js:109:61
<< RFB.connect util.js:108:61
The Components object is deprecated. It will soon be removed. fed78575-7f74-4ae0-9bbd-1f3c54e170c8
Firefox can’t establish a connection to the server at ws://localhost:17523/.
websock.js:285:36
Firefox can’t establish a connection to the server at ws://192.168.0.10/ws/1/fed78575-7f74-4ae0-9bbd-1f3c54e170c8. websock.js:333:20
>> WebSock.onerror: [object Event]
WebSocket on-error event util.js:110:61
<< WebSock.onerror util.js:108:61
>> WebSock.onclose util.js:108:61
WebSocket on-close event util.js:110:61
>> Keyboard.allKeysUp util.js:108:61
<< Keyboard.allKeysUp util.js:108:61
New state 'failed', was 'connect'. Msg: Server disconnected (code: 1006) util.js:111:61
Clearing connect timer util.js:108:61
<< WebSock.onclose util.js:108:61
>> Keyboard.allKeysUp util.js:108:61
<< Keyboard.allKeysUp util.js:108:61
New state 'disconnected', was 'failed'. util.js:110:61
Firefox can’t establish a connection to the server at ws://localhost:17523/. websock.js:285:36

​

**Comment by dantti** [comment]
googling I found several issues that states that Squid does not support Websockets the way we need it:
http://lists.squid-cache.org/pipermail/squid-users/2017-January/013953.html
