### ISSUE TITLE
QtConcurrent

### ISSUE THREAD

**Issue by haralambop** [cutelyst/Virtlyst#35]
Hi 
I am trying to connect to remote libvirtd instances using QtConcurrent 
I replaced in the updateConnections the line
server->conn = new Connection(url, name, server);
with 
future[i++] = QtConcurrent::run(connect_func, server,url,name,id);
but i receive an error
QObject: Cannot create children for a parent that is in a different thread.

My question is:
How can I correct use the QtConcurrent in cutelyst?

**Comment by dantti** [comment]
You can use QtConcurrent as long as what you are using is thread-safe, and virtlyst classes aren't.
