### ISSUE TITLE
Screenshot broken

### ISSUE THREAD

**Issue by liamdawson** [cutelyst/Virtlyst#38]
As per `tinypic.com`:

> 
> TinyPic Has Ceased Operations
>
> Due to an inability to support a high-quality free digital service that derives 100% of its revenue from ever declining on-site revenues, TinyPic has shut down its operations. As previously announced on this website, September 16, 2019 was the last day for our users to access their accounts to download their images.
>
> What Should You Do Now?
> 
> We recommend checking out our sister company, Photobucket, for image hosting. They are currently offering an unlimited image hosting and storage plan for $5 per month (regularly priced at $11.99 per month). We would like to personally thank you for choosing TinyPic as your hosting service. Many of you have been utilizing our services since we launched back in April 2004.

**Comment by dantti** [comment]
fixed
