### ISSUE TITLE
csrf

### ISSUE THREAD

**Issue by aharalambopoulos** [cutelyst/Virtlyst#40]
I am trying to activate csrf in virtlyst following the instructions described  here https://api.cutelyst.org/classCutelyst_1_1CSRFProtection.html 
but I get this error

 cutelyst.core[critical] "Error while rendering template: Invalid block tag on line 0: 'c_csrf_token', expected 'endblock', line 0, login.html, line 0, login.html"

**Comment by iastinf** [comment]
> I am trying to activate csrf in virtlyst following the instruction here https://api.cutelyst.org/classCutelyst_1_1CSRFProtection.html
> but I get this error

**Comment by dantti** [comment]
This is likely due Grantlee not finding and loading the grantlee_cutelyst plugin, I need to port to Cutelee to make this easier...

**Comment by dantti** [comment]
it has been ported, please do a PR if you still want this.
