### ISSUE TITLE
Cannot set Port for SSH

### ISSUE THREAD

**Issue by julian-w** [cutelyst/Virtlyst#57]
Hello,

I'm trying to connect to a server via SSH that uses a non-default port instead of the standard port 22. I followed the instructions ("If you have another SSH port on your server, you can add IP:PORT like '192.168.1.1:2222'"), but this approach isn’t working.

The log shows the following message: 
`virtlyst  | 7:7 virt.connection[warning] Failed to open connection to QUrl("qemu+ssh://root@/system")`

If I remove the ":PORT" portion from the FQDN/IP, the system at least attempts to connect to the IP using the default port.

It seems the "setHost" function may not be the right choice:

https://github.com/cutelyst/Virtlyst/blob/039c6f6261d7163353f4389d8e384a85ad6497ac/src/virtlyst.cpp#L281

https://doc.qt.io/qt-6/qurl.html#setHost
https://stackoverflow.com/questions/23793411/how-to-parse-network-hostname-port-in-qt

**Comment by dantti** [comment]
indeed, parsing and setPort are required, please create a PR :)

**Comment by julian-w** [comment]
Thank you for the quick merge, it's working now :-)
